### ISSUE TITLE
Not working in Angular Environment

### ISSUE THREAD

**Issue by GMuthuraja** [AndresMorelos/ssl-information#2]
`import { certManager } from 'ssl-information';`

After adding below lines inside the ngOnInit() and run ng serve
`certManager.get({ host: 'www.google.com' }).then((cert) => console.log(cert)).catch((err) => console.error(err));`

I caught below error in browser console.
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getPeerCertificate' of undefined

Above code works in node app but not works in Angular. Please help me to resolve this.

**Comment by AndresMorelos** [comment]
@GMuthuraja For sure, I will take a look at this. I'll keep you posted

**Comment by AndresMorelos** [comment]
@GMuthuraja May I know the Angular version that you are using?

Since Angular works on the client-side (browser), it doesn't have access to NodeJS Libraries, I will need to implement a workaround to get send the request through XHR and get the certificate to give the results.

**Comment by GMuthuraja** [comment]
@AndresMorelos Thanks for the update. I'm using Angular ~v8.2.14.

**Comment by GMuthuraja** [comment]
@AndresMorelos Is there any solution ?

**Comment by AndresMorelos** [comment]
@GMuthuraja After too many tries I found an [MZN article ](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/How_to_check_the_secruity_state_of_an_XMLHTTPRequest_over_SSL) that says to get the certificate information requires elevated privileges, so, any page is not able to get the SSL information of a site through XHR.

Maybe a good approach is to offer a backend service  from a NodeJS server to get the SSL information.
